# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Rabia Kuran/PycharmProjects/veriOnislemeOdev/qt_designerr.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 240, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 370, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 240, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 370, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 160, 241, 41))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 240, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 310, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 430, 291, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton.setGeometry(QtCore.QRect(50, 90, 241, 51))
        self.PushButton.setObjectName("PushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 310, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 310, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(400, 70, 661, 541))
        self.tableView.setObjectName("tableView")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(50, 470, 321, 141))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Medyan"))
        self.pushButton_7.setText(_translate("MainWindow", "Bes Sayi Ozeti"))
        self.pushButton.setText(_translate("MainWindow", "Ortalama"))
        self.pushButton_8.setText(_translate("MainWindow", "Kutu Grafigi"))
        self.comboBox.setItemText(0, _translate("MainWindow", "n1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "n2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "n3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "n4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "n5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "n6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "n7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "n8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "n9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "n10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "n11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "n12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "n13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "n14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "n15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "n16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "n17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "n18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "n19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "n20"))
        self.comboBox.setItemText(20, _translate("MainWindow", "n21"))
        self.comboBox.setItemText(21, _translate("MainWindow", "n22"))
        self.comboBox.setItemText(22, _translate("MainWindow", "n23"))
        self.comboBox.setItemText(23, _translate("MainWindow", "n24"))
        self.comboBox.setItemText(24, _translate("MainWindow", "n25"))
        self.comboBox.setItemText(25, _translate("MainWindow", "n26"))
        self.comboBox.setItemText(26, _translate("MainWindow", "n27"))
        self.comboBox.setItemText(27, _translate("MainWindow", "n28"))
        self.comboBox.setItemText(28, _translate("MainWindow", "n29"))
        self.comboBox.setItemText(29, _translate("MainWindow", "n30"))
        self.comboBox.setItemText(30, _translate("MainWindow", "n31"))
        self.comboBox.setItemText(31, _translate("MainWindow", "n32"))
        self.comboBox.setItemText(32, _translate("MainWindow", "n33"))
        self.comboBox.setItemText(33, _translate("MainWindow", "n34"))
        self.pushButton_3.setText(_translate("MainWindow", "Mod"))
        self.pushButton_6.setText(_translate("MainWindow", "Aykırı Degerler"))
        self.pushButton_9.setText(_translate("MainWindow", "Varyans ve Standart Sapma"))
        self.PushButton.setText(_translate("MainWindow", "Eksik Veri Tamamla"))
        self.pushButton_4.setText(_translate("MainWindow", "Frekans"))
        self.pushButton_5.setText(_translate("MainWindow", "IQR"))
        self.label.setText(_translate("MainWindow", "                   VERİ ÖNİSLEMEYE GİRİŞ"))

